### ISSUE TITLE
Letter "k" defect

### ISSUE THREAD

**Issue by kadfak** [FAlthausen/Vollkorn-Typeface#29]
Letter "k" seems to have a little patch in it which I would assume should not be there.

![g9561](https://user-images.githubusercontent.com/17338808/69221013-edb3f480-0b7e-11ea-8708-20f5ae118e4d.png)

**Comment by FAlthausen** [comment]
This is in the varfont, right? (This shouldn’t happen with the standard ttfs.)
cc @m4rc1e

**Comment by kadfak** [comment]
Yes, seems to be a varfont problem.

**Comment by FAlthausen** [comment]
Varfonts of Vollkorn apparently are gonna be reworked currently (but not by me):
https://github.com/FAlthausen/Vollkorn-Typeface/issues/28#issue-507225045

**Comment by matthewjdye** [comment]
Hey, just out of curiosity, is this issue going to ever get addressed?  It’s now present in whatever font version appears in Google Docs and it’s really irritating (having said that, I’m really digging the new weights and extra characters from version 4.1).

**Comment by matthewjdye** [comment]
Also, not to pile on, but you can even see it on @FAlthausen’s personal website:
![image](https://user-images.githubusercontent.com/2635313/82857689-5b96fb00-9ed7-11ea-99e5-e26b22de8ef3.png)

**Comment by m4rc1e** [comment]
@moyogo @pichotta can confirm this is in the vf. Can we roll a fix please?

<img width="323" alt="Screenshot 2020-05-26 at 08 45 31" src="https://user-images.githubusercontent.com/7525512/82874121-67ada780-9f2d-11ea-9976-ed8203441658.png">

**Comment by pichotta** [comment]
@m4rc1e 
This is issue should now be fixed in today's new build.  It appears that Glyphs to RF conversion has difficulty with the path directions with the outline structure shown below. Presumably it has to do with the crossover of outlines at the apex which occurs twice in the same contour. All styles should still be checked visually for possible occurrence in other glyphs.

<img width="979" alt="Vollkorn :k outline structure" src="https://user-images.githubusercontent.com/6576107/83921854-4b8be080-a74d-11ea-9f37-52252cbcec21.png">

**Comment by pichotta** [comment]
@m4rc1e 

Fixing a few more open corner and crossing outline artifacts from Vollkorn review.

![Vollkorn 2020-06-11 at 11 19 42 PM](https://user-images.githubusercontent.com/6576107/84461419-6cb36c00-ac3a-11ea-819a-7f37d71a9920.png)

![Vollkorn 2020-06-11 at 11 19 55 PM](https://user-images.githubusercontent.com/6576107/84461428-70df8980-ac3a-11ea-8829-2b6f6e872761.png)

**Comment by m-dye** [comment]
Hey, I really hate to be a pest, and I know this issue was closed, but I do not see a fix on the Google Fonts site. This screenshot was taken just this second. Is the plan to just accept it? The issue has persisted for over a year now.

![image](https://user-images.githubusercontent.com/2635313/100264097-fb2f5780-2f13-11eb-89ff-908e5c8c72d2.png)

**Comment by pichotta** [comment]
Confirming the fix was made to the /k on June 5, 2020

The /k in the current roman .ttfs does not have this overlap. 
It does not appear in the VF file Vollkorn[wght].ttf  with a visual check above 300 pixels.
https://github.com/TypeNetwork/Vollkorn-Typeface

It likely needs another push upstream.  Last one was May 6th.

I see one open Issue related to broswers and service
https://github.com/TypeNetwork/Vollkorn-Typeface/issues/8
